# List 1
list1 = [
    "ATHARV GOPAL GAWANDE",
    "Siddharth Sunil Kalamkar",
    "Jayesh Ulhas Naphade",
    "Sudarshan Suresh Bhosale",
    "Yosha Jitendra Mahajan",
    "Onkar Ulhas Akirke",
    "Gaurav Maroti Vadle",
    "Pratik Sandip Minde",
    "Vishal Anil Palve",
    "Aditya Arunrao Adhane",
    "Ruturaj Pandurang Mundhe",
    "Mrudula Prakash Shinde",
    "Yash Suresh Chhajed",
    "Rishvi  Kumari",
    "Keshav Kumar Sah",
    "Rohit Suresh Kakade",
    "Prathamesh Nitin Sohoni",
    "Ganesh Navanath Misal",
    "Ayush Ashutosh Naik",
    "Yash Machhindra Ghodake",
    "Rajesh Bharat More",
    "Pawan Dadaso Kumbhar",
    "Shubham Raju Sagar",
    "Anuja Sanjay Phalake",
    "Tejas Subhash Arangale",
    "Rinku Vijay Bhagwat",
    "Yuvraj Bapusaheb Darekar",
    "Vishal Rajkumar Sangole",
    "Abhijit Balasaheb Nikat",
    "Shrihari Ajinath Waykule",
    "Suyash Satish Shinde",
    "saprem prashant pandit",
    "Pratik Sayaji Patil",
    "Harsh  Rathore",
    "Pritam Bharat Patil",
    "Asavari Santosh Nikam",
    "SURAJ RAM MAPARI",
    "KUNAL RAJENDRA MORE",
    "Adarsh Rajesh Pandey",
    "Abhishek Bapu Ghodake",
    "Nikhil Anil Yadav",
    "Praneet Linganna Sadawari",
    "Vaishnavi Yogesh Chavan",
    "Laxmiputra Ravindra Birajdar",
    "Sakshi Rajendra Khatal",
    "Revati Rajkumar Talekar",
    "Chinmay Makrand Pimpalgaonkar",
    "Hemant Vitthal Thorat",
    "Kshitij Ajit Kondedeshmukh",
    "Chetan Baliram Patil",
    "Vaibhav Achyutrao Ugale",
    "Avishkar  Kotkar",
    "Omkar Vishnu Lingayat",
    "Pratiksha Prakash Jadhav",
    "Anshul Harish Pathrabe",
    "Saurabh Satish Zagade",
    "Vikash  Kumar",
    "Abhimannyu Arjun Magar",
    "Shruti Sachin Salunkhe",
    "Shreya Sanjay Deokar",
    "Shubham Hemant Vaidya",
    "Prerana Kailas Shinde",
    "Yashraj  Thelkar",
    "Amey Madhusudhan Kulkarni",
    "Nikhil Dipak Bagal",
    "Hrishikesh Ramchandra Marathe",
    "Chaitanya Moreshwar Padalkar",
    "Sampada Anil Bhosale",
    "Yash Manmath Swami",
    "Rushikesh Arun Matele",
    "Gaurav Dinesh Sakure",
    "Aryan  Srivastava",
    "Shubham Bhagwan Jadhav",
    "KUNAL APPA VEER",
    "Sajal  Priya",
    "Omkar Chandrakant Bedake",
    "Deepak Ramesh Moolya",
    "DALJEET  SINGH",
    "Saurabh Ramesh Borude",
    "Shalaka Uday Mande",
    "Himanshu Vijay Kapse",
    "Prajwal Bapurao Salunke",
    "Sanket Sunil Salunkhe",
    "Rajeev Ranjan Rai",
    "Aditya Dinesh Nimse",
    "Nikita Vijay Pawar",
    "Mangesh Rajendra Kokare",
    "Viraj Sachin Sonawane",
    "Mayuri Ramchandra Pawar",
    "Vidya  Kale",
    "SAMARTH MACHHINDRA ADKITTE",
    "Tanwi  Gaikwad",
    "Dinesh Maruti Bhatlawande",
    "Ishant Rajesh Patil",
    "Nakul Harban Dandekar",
    "Prathmesh Sanjay Ugale",
    "Sarang Dayanand Jaybhaye",
    "Vinay Hanumant Khalate",
    "Dewang Girish Sampgaonkar",
    "Shubham Vinayak Sadigale",
    "Atharva Nanasaheb Patil",
    "Aryan Subhash Gaikwad",
    "Rushikesh Shekhar Pawar",
    "Vaishnavi Dnyaneshwar Karanjkar",
    "Milind  Pushpam",
    "Mayur Mohanlal Nigade",
    "Deepraj Bharat Patil",
    "Abhishek Gajanan Mudhol",
    "Sumit Vikas Pawar",
    "Prathamesh Ajay Gaikwad",
    "LOKESH RAJENDRA KHADSE",
    "Chaitanya Umesh Pole",
    "Madhav Sandeep Lonkar",
    "Vyankatesh Dnyanoba Pete",
    "Umesh Vinayak Unde",
    "PRAMOD MAYAPPA DEVAKATE",
    "Kaustubh Hemant Joshi",
    "Amit Madhav Jadhav",
    "Mayuri Baliram Gund",
    "Rasika Santosh Sherkar",
    "Harshwardhan Babasaheb Darade",
    "Pranjali Santosh Patil",
    "Rishu  Rai",
    "Abhishek Dattatray Linge",
    "Aditi Sandip Kulkarni",
    "Anuj Vinod Patil",
    "Vinay Brahmadev Sable"
]

# List 2
list2 = [
    "Suyash Satish Shinde",
    "Pritam Bharat Patil",
    "DALJEET  SINGH",
    "PRAMOD MAYAPPA DEVAKATE",
    "Ganesh Navanath Misal",
    "Chetan Baliram Patil",
    "Jayesh Ulhas Naphade",
    "saprem prashant pandit",
    "Ayush Ashutosh Naik",
    "Saurabh Ramesh Borude",
    "Pratiksha Prakash Jadhav",
    "Praneet Linganna Sadawari",
    "Om Sunil Udavant",
    "Sakshi Suresh Fand",
    "Pruthviraj Santosh Mali",
    "R  AJAY",
    "Rahul Madhukar Khandvi",
    "Nitin Balu Nikam",
    "Kiran Vijaykumar Shende",
    "Ved Sandeep Deshmukh",
    "Nikhil Anil Kurle",
    "Sayali Sunil Lohokare",
    "Neha Nandkishor Devharkar",
    "Tejas Baburao Katke",
    "Sudhir Hanmant Takale",
    "Vedant Umesh Saikhede",
    "Vaishnavi Upendra Pote",
    "Omkar Santosh Khandebharad",
    "Ankush Dnyaneshwar Pawar",
    "Preshit Prashant Satalgaonkar",
    "Aviraj Bhausaheb Latpate",
    "Swapnil Appasaheb Dhamdhere",
    "Chinmay Makrand Pimpalgaonkar",
    "ATHARV GOPAL GAWANDE",
    "Yuvraj Bapusaheb Darekar",
    "Vinay Hanumant Khalate",
    "Dewang Girish Sampgaonkar",
    "Adarsh Rajesh Pandey",
    "Aryan Subhash Gaikwad",
    "Mrudula Prakash Shinde",
    "Rishvi  Kumari",
    "Laxmiputra Ravindra Birajdar",
    "Asavari Santosh Nikam",
    "Mangesh Rajendra Kokare",
    "Keshav Kumar Sah",
    "Harsh  Rathore",
    "Prathamesh Nitin Sohoni",
    "Rohit Suresh Kakade",
    "Sarang Dayanand Jaybhaye",
    "Viraj Sachin Sonawane",
    "Yosha Jitendra Mahajan",
    "Ruturaj Pandurang Mundhe",
    "Vinay Brahmadev Sable",
    "Dinesh Maruti Bhatlawande",
    "Kalpesh Anand Pawar",
    "Rushikesh Sadhu Harpude",
    "Vaishnavi Naval Chaudhari",
    "Sudarshan Achyut Gaikwad",
    "Nikhil Balasaheb Neel",
    "Vinod Shivaji Asabe",
    "Abhishek Indal Thakur",
    "Nandkumar Sambhaji Chavan",
    "Aditya Suresh Shahare",
    "Shivanjali Shriram Shinde",
    "Akshay Nandkumar Kolhe",
    "Vishal Rajendra Puri",
    "Sairam Himmat More",
    "Mandar Nitin Umare",
    "Yash Hemant Wagh",
    "Manjiri Raghu Shinde",
    "Pradnya Subhash Thombare",
    "Abhinandan  Jain",
    "Aditya Arunrao Adhane",
    "Shrihari Ajinath Waykule",
    "Aditi Sandip Kulkarni",
    "Hemant Vitthal Thorat",
    "Shreya Sanjay Deokar",
    "Vaishnavi Dnyaneshwar Karanjkar",
    "Madhav Sandeep Lonkar",
    "Revati Rajkumar Talekar",
    "Shubham Raju Sagar",
    "Yash Manmath Swami",
    "Sanket Sunil Salunkhe",
    "Nikhil Anil Yadav",
    "SURAJ RAM MAPARI",
    "KUNAL RAJENDRA MORE",
    "Amey Madhusudhan Kulkarni",
    "Rajeev Ranjan Rai",
    "Pawan Dadaso Kumbhar",
    "Amit Madhav Jadhav",
    "Rasika Santosh Sherkar",
    "Bhagyashri Sunil patil",
    "Akash Himmatrao Tale",
    "VINAY ANIL MAHAJAN",
    "Lina Prashant Gharate",
    "Kirti Mallikarjun Chaugule",
    "Fiyona Piyush Shah",
    "Avadhut Mohan Shilimkar",
    "Raj Jaywant Mulik",
    "Shubham Shrishail Mangalure",
    "Abhishek Sameer Pawar",
    "Kshitij Dnyaneshwar Lavhe",
    "Rushikesh Santosh Doke",
    "Prerna Vivek Gatmane",
    "Namrata Subhash Pradhan",
    "Prashila Prakash Mali",
    "Mohit Jayesh kumar Jain",
    "Vishal Sanjivkumar Patil",
    "Nidhi Raychand Bhandari",
    "Mithil Jagdish Modani",
    "Sangam Prabhu Swami",
    "Rutuja Hemant Getme",
    "Additye  kadam",
    "Padmaja Anil Penshanwar"
]


matching_names = [name for name in list1 if name in list2]

# Count of matching names
count_matching_names = len(matching_names)

# Print matching names and count
print("Matching Names:")
for name in matching_names:
    print(name)

print("Count of Matching Names:", count_matching_names)